### ISSUE TITLE
Not able to make OAUTH Post call

### ISSUE THREAD

**Issue by tanujChilwal** [mrjones/oauth#64] opened 2017-02-25 08:07 UTC
I am trying to make a POST call to remote server which has **OAUTH** like this

**globals.Consumer.PostJson(URL, postBody, globals.AccessToken)**
This works absolutely fine if I make GET call to the same remote server.

I always get **"Internal Server Error"** 
Any suggestions.

**Comment by mrjones** [comment] 2017-02-25 17:14
Hi!  Unfortunately, I'm not able to reproduce this behavior.

For example, the POST request in the twitter example works for me.  I ran:
$ go run examples/twitter/twitter.go --consumerkey $MY_CONSUMER_KEY --consumersecret $MY_CONSUMER_SECRET --postupdate

And it created this twitter update, via an HTTP POST request:
https://twitter.com/m_r_j_api/status/835537361127747584

There could still be a bug in the library, but it could also be in the server you're connecting to, or in your code.  It's hard for me to say without more information.

I'm going to close this for now, but feel free to re-open with more information!

**Closed by mrjones** 2017-02-25 17:14 UTC

**Comment by tanujChilwal** [comment] 2017-02-27 16:54
thanks a lot for replying . This was issue on my end. Sorry for the
inconvenience.
